#!/bin/bash

VERSION="${1:-NULL}"
URL="${2:-NULL}"
TAGFILE=".template/support-tags.md"

if [ "$VERSION" == "NULL" ] || [  "$URL" == "NULL" ];then
  echo "$0 need version and url. Ex.: $0 \"0.12.9\" \"https://github.com/gogs/gogs/releases/tag/v0.12.9\""
  exit 1
fi

FIRST_TAG=$(grep -v  "^<" .template/support-tags.md)

if [ "${FIRST_TAG}" == "" ];then
  # Only github url are supported
  echo "- [latest]($URL)" >> $TAGFILE
fi

IS_EXISTES=$(grep -c "$VERSION" .template/support-tags.md)

if [ "$IS_EXISTES" == "0" ];then
    sed -i "2a - [$VERSION]($URL)" .template/support-tags.md
else
    echo "$VERSION is exist,skip add version."
fi
