#!/bin/bash

TAGS="${1:-NULL}"
TAGFILE=".template/release-tags.md"

. /usr/sbin/meta.env

if [ "$TAGS" == "NULL" ];then
  echo "$0 need tag. Ex.: $0 \"0.12.9\""
  exit 1
fi

IS_EXISTES=$(grep -c "$TAGS" $TAGFILE)

if [ "$IS_EXISTES" == "0" ];then
  echo "* [\`latest\`, \`$TAGS\`](https://github.com/quicklyon/$app_name-docker/blob/${TAGS}/Dockerfile)" > $TAGFILE
else
    echo "$TAGS is exist,skip update."
fi
