#!/bin/bash
# shellcheck disable=SC1091

[ -n "${DEBUG:+1}" ] && set -x

. /usr/sbin/meta.env

if [ "$1" == "-v" ];then
    render-template .template/readme.md.tpl
else
    render-template .template/readme.md.tpl > README.md
fi